import os
import datetime


def document_saver(response_text : str,directory:str="../output"):

    os.makedirs(directory,exist_ok=True)

    final_text = f"""
    🌍 AI Travel Plan

    # **Generated:** {datetime.datetime.now().strftime('%Y-%m-%d at %H:%M')}  
    # **Created by:** Atriyo's Travel Agent

    ---

    {response_text}

    ---

    *This travel plan was generated by AI. Please verify all information, especially prices, operating hours, and travel requirements before your trip.*

    """

    filename = f"{directory}/AI Travel Planner-{datetime.datetime.now().strftime('%Y-%m-%d at %H:%M')}.md"

    with open(filename,"w") as obj:
        obj.write(final_text)
    
    print(f"{filename} has been saved")

